name: Deploy Alcivar Application

on:
  push:
    branches: "main"

permissions:
    contents: read
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/italdao/alcivar:1.0.1
        
    - name: Copiar stack.yml to VPS (SCP)
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/deploy"
    
    - name: Desplegar los servicios en la web
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          set -e
          mkdir -p ~/deploy
          cd ~/deploy

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u  italdao  --password-stdin
          docker pull ghcr.io/italdao/alcivar:1.0.1

          STACK_NAME="alcivar"
          STACK_FILE="stack.yml"

          echo "==> Comprobando si el stack '${STACK_NAME}' existe..."
          if docker stack ls --format '{{.Name}}' | grep -qw "${STACK_NAME}"; then
            echo "==> El stack '${STACK_NAME}' existe â€” procediendo a eliminarlo..."
            docker stack rm "${STACK_NAME}" || true

            echo "==> Esperando a que los servicios del stack se detengan..."
            SECONDS_WAITED=0
            INTERVAL=5
            TIMEOUT=60
            while docker stack ls --format '{{.Name}}' | grep -qw "${STACK_NAME}"; do
              if [ "$SECONDS_WAITED" -ge "$TIMEOUT" ]; then
               echo "Timeout esperando la eliminacion del stack despues de ${TIMEOUT}s."
                break
              fi
              echo "  ...esperando ${INTERVAL}s (llevado ${SECONDS_WAITED}s)"
              sleep $INTERVAL
              SECONDS_WAITED=$((SECONDS_WAITED + INTERVAL))
            done
          else
            echo "==> No existe el stack '${STACK_NAME}', continuo..."
          fi
          
          echo "==> Desplegando stack '${STACK_NAME}' desde ${STACK_FILE}..."
          docker stack deploy --with-registry-auth -c "${STACK_FILE}" "${STACK_NAME}"
          
          echo "==> Verificando estado..."
          docker service ls
          docker stack ps "${STACK_NAME}"
